### ISSUE TITLE
We tried your method and got output like this

### ISSUE THREAD

**Issue by gyc9709** [vhchuong1997/Saliency-prediction-for-360-degree-video#10]
![1](https://user-images.githubusercontent.com/36316764/147573200-5a26cb97-496a-45a6-b279-1e5e0913055e.png)

And we find your code for test:
![2](https://user-images.githubusercontent.com/36316764/147573273-0c047ec0-b3cc-4bfc-b3ac-5413190d2c1f.png)

What is the meaning of parameter of 30 and 300?

Hope for your reply

**Comment by vhchuong** [comment]
Hello! 
In the saving file procedure, we scale the values of the pixels in the output up so that they would appear to be easier to witness through the human eyes. The evaluation results are not affected by this.

**Comment by gyc9709** [comment]
Thanks for your reply. So is the result shown right (img1 in your code)?

> Hello! In the saving file procedure, we scale the values of the pixels in the output up so that they would appear to be easier to witness through the human eyes. The evaluation results are not affected by this.
